#pragma once

/**
 * Enumerations
 *
 */

enum UNIT_TYPE
{
    UNIT_TYPE_CAR = 1,
    UNIT_TYPE_TANK = 2,
    UNIT_TYPE_SUPER = 3,
    UNIT_TYPE_LAUNCHER = 4,
    UNIT_TYPE_NUKER = 5,
    UNIT_TYPE_MINER = 6,
    UNIT_TYPE_END
};
enum BUILDING_TYPE
{
    BUILDING_TYPE_MINE = 51,
    BUILDING_TYPE_FACTORY = 52,
    BUILDING_TYPE_YARD = 53,
    BUILDING_TYPE_PLANT = 54,
    BUILDING_TYPE_BORE = 55,
    BUILDING_TYPE_RADAR = 56,
    BUILDING_TYPE_SCIENCE = 57,
    BUILDING_TYPE_SILO = 58,
    BUILDING_TYPE_GUNTOWER = 59,
    BUILDING_TYPE_CANTOWER = 60,
    BUILDING_TYPE_END
};
