#pragma once

/**
 * Enumerations
 *
 */

enum UNIT_TYPE
{
    UNIT_TYPE_CAR = 0,
    UNIT_TYPE_TANK,
    UNIT_TYPE_LAUNCHER,
    UNIT_TYPE_SUPER,
    UNIT_TYPE_NUKER,
    UNIT_TYPE_END
};
enum BUILDING_TYPE
{
    BUILDING_TYPE_PLANT = 0,
    BUILDING_TYPE_FACTORY,
    BUILDING_TYPE_YARD,
    BUILDING_TYPE_BORE,
    BUILDING_TYPE_RADAR,
    BUILDING_TYPE_SCIENCE,
    BUILDING_TYPE_SILO,
    BUILDING_TYPE_GUNTOWER,
    BUILDING_TYPE_CANTOWER,
    BUILDING_TYPE_END
};
